baseURL = "https://lukasferrari.com"
title = "Lukas Ferrari"
theme = "gokarna"
languageCode = "de"
defaultContentLanguage = "de"
enableEmoji = true
enableRobotsTXT = true

pygmentsStyle = "monokai"

[params]
  footer = "Lukas Ferrari"
  description = "Dolmetscher, Übersetzer, Kulturmittler."
  avatarURL = "/images/logo.svg"
  AvatarAltText = "avatar"
  avatarSize = "size-l"
  customHeadHTML = """
    <link rel="stylesheet" href="/style.css">
  """

  socialIcons = [
    {name = "email", url = "mailto:mail@lukasferrari.com"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Über mich"
    # pre = "<span data-feather='code'></span>"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Referenzen"
    # pre = "<span data-feather='code'></span>"
    url = "/references/"
    weight = 3

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
