baseURL = "https://gokarna-hugo.netlify.app"
title = "Lukas Ferrari"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

pygmentsStyle = "monokai"

[params]
  footer = "Lukas Ferrari"
  description = "comprensione per tutti"
  avatarURL = "/images/logo.svg"
  AvatarAltText = "avatar"
  avatarSize = "size-l"

  socialIcons = [
    {name = "twitter", url = "https://example.com"},
    {name = "linkedin", url = "https://www.linkedin.com/in/lukas-ferrari-ba0bb6259/"},
    {name = "instagram", url = "https://example.com"},
    {name = "email", url = "mailto:example@example.com"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    # pre = "<span data-feather='code'></span>"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "References"
    # pre = "<span data-feather='code'></span>"
    url = "/references/"
    weight = 3

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
